//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comisiones
    {
        public int id { get; set; }
        public int id_empresa { get; set; }
        public decimal rango_inferior { get; set; }
        public decimal rango_superior { get; set; }
        public decimal monto_comision { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public int usuario_modificacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
