//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int id { get; set; }
        public int id_usuario_compra { get; set; }
        public string codigo_recaudacion { get; set; }
        public byte pagado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<decimal> monto_cobrar { get; set; }
        public string numero_factura { get; set; }
        public decimal monto_comision { get; set; }
        public decimal monto_parcial { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
