//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Lugares
    {
        public Lugares()
        {
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int id { get; set; }
        [DisplayName("Lugar")]
        public string nombre_lugar { get; set; }
        public string direccion { get; set; }
        public int capacidad_maxima { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
    
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}
