//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TNTEntities : DbContext
    {
        public TNTEntities()
            : base("name=TNTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compra> Compra { get; set; }
        public DbSet<Empresas> Empresas { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<Lugares> Lugares { get; set; }
        public DbSet<Personas> Personas { get; set; }
        public DbSet<sectores> sectores { get; set; }
        public DbSet<Suscripcion> Suscripcion { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<Tipos_evento> Tipos_evento { get; set; }
        public DbSet<token_usuario> token_usuario { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<comisiones> comisiones { get; set; }
        public DbSet<Puntos_pago> Puntos_pago { get; set; }
        public DbSet<imei_validos> imei_validos { get; set; }
        public DbSet<EnviosRelegadosSINTESIS> EnviosRelegadosSINTESIS { get; set; }
    }
}
