//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectores
    {
        public sectores()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public decimal precio_unitario { get; set; }
        public int id_evento { get; set; }
        public int asientos_disponibles { get; set; }
        public string img_url { get; set; }
        public bool es_sector_numerado { get; set; }
        public int filas { get; set; }
        public int columnas { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
