//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripcion
    {
        public int id { get; set; }
        public int id_persona { get; set; }
        public int id_tipo_evento { get; set; }
        public System.DateTime fecha_suscripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Tipos_evento Tipos_evento { get; set; }
    }
}
