//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string codigo { get; set; }
        public string butaca { get; set; }
        public int id_evento { get; set; }
        public Nullable<byte> valida { get; set; }
        public bool utilizada { get; set; }
        public Nullable<int> id_sector { get; set; }
        public string codigo_recaudacion { get; set; }
        public Nullable<System.DateTime> fecha_uso { get; set; }
        public string nombre_usuario { get; set; }
        public string nit_usuario { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public decimal costo_sin_comision { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual sectores sectores { get; set; }
    }
}
