//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Tipos_evento
    {
        public Tipos_evento()
        {
            this.Eventos = new HashSet<Eventos>();
            this.Suscripcion = new HashSet<Suscripcion>();
        }
    
        public int id { get; set; }

        [DisplayName("Descripción")]
        public string descripcion { get; set; }
        public string img_url { get; set; }
    
        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual ICollection<Suscripcion> Suscripcion { get; set; }
    }
}
