//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class token_usuario
    {
        public string token { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_generacion { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
