//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Compra = new HashSet<Compra>();
            this.Empresas = new HashSet<Empresas>();
            this.Personas = new HashSet<Personas>();
            this.token_usuario = new HashSet<token_usuario>();
            this.comisiones = new HashSet<comisiones>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Empresas> Empresas { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
        public virtual ICollection<token_usuario> token_usuario { get; set; }
        public virtual ICollection<comisiones> comisiones { get; set; }
    }
}
