//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNT.WebSintesis_externo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosItem", Namespace="http://www.openuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatosItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idTransaccionField;
        
        private int numeroPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TNT.WebSintesis_externo.DItem[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.transaccionField, value) != true)) {
                    this.transaccionField = value;
                    this.RaisePropertyChanged("transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.idTransaccionField, value) != true)) {
                    this.idTransaccionField = value;
                    this.RaisePropertyChanged("idTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int numeroPago {
            get {
                return this.numeroPagoField;
            }
            set {
                if ((this.numeroPagoField.Equals(value) != true)) {
                    this.numeroPagoField = value;
                    this.RaisePropertyChanged("numeroPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TNT.WebSintesis_externo.DItem[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DItem", Namespace="http://www.openuri.org/")]
    [System.SerializableAttribute()]
    public partial class DItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int numeroItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        private double precioUnitarioField;
        
        private int cantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroItem {
            get {
                return this.numeroItemField;
            }
            set {
                if ((this.numeroItemField.Equals(value) != true)) {
                    this.numeroItemField = value;
                    this.RaisePropertyChanged("numeroItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                if ((this.precioUnitarioField.Equals(value) != true)) {
                    this.precioUnitarioField = value;
                    this.RaisePropertyChanged("precioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespItem", Namespace="http://www.openuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codError {
            get {
                return this.codErrorField;
            }
            set {
                if ((this.codErrorField.Equals(value) != true)) {
                    this.codErrorField = value;
                    this.RaisePropertyChanged("codError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionErrorField, value) != true)) {
                    this.descripcionErrorField = value;
                    this.RaisePropertyChanged("descripcionError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosPlanilla", Namespace="http://www.openuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatosPlanilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nit_CI_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoClienteField;
        
        private int codigoEmpresaField;
        
        private int fechaField;
        
        private int horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoRecaudacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionRecaudacionField;
        
        private int fechaVencimientoField;
        
        private int horaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TNT.WebSintesis_externo.DPlanilla[] planillasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.transaccionField, value) != true)) {
                    this.transaccionField = value;
                    this.RaisePropertyChanged("transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nit_CI_cliente {
            get {
                return this.nit_CI_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nit_CI_clienteField, value) != true)) {
                    this.nit_CI_clienteField = value;
                    this.RaisePropertyChanged("nit_CI_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoClienteField, value) != true)) {
                    this.codigoClienteField = value;
                    this.RaisePropertyChanged("codigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int codigoEmpresa {
            get {
                return this.codigoEmpresaField;
            }
            set {
                if ((this.codigoEmpresaField.Equals(value) != true)) {
                    this.codigoEmpresaField = value;
                    this.RaisePropertyChanged("codigoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int hora {
            get {
                return this.horaField;
            }
            set {
                if ((this.horaField.Equals(value) != true)) {
                    this.horaField = value;
                    this.RaisePropertyChanged("hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.monedaField, value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string codigoRecaudacion {
            get {
                return this.codigoRecaudacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRecaudacionField, value) != true)) {
                    this.codigoRecaudacionField = value;
                    this.RaisePropertyChanged("codigoRecaudacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string descripcionRecaudacion {
            get {
                return this.descripcionRecaudacionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionRecaudacionField, value) != true)) {
                    this.descripcionRecaudacionField = value;
                    this.RaisePropertyChanged("descripcionRecaudacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                if ((this.fechaVencimientoField.Equals(value) != true)) {
                    this.fechaVencimientoField = value;
                    this.RaisePropertyChanged("fechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int horaVencimiento {
            get {
                return this.horaVencimientoField;
            }
            set {
                if ((this.horaVencimientoField.Equals(value) != true)) {
                    this.horaVencimientoField = value;
                    this.RaisePropertyChanged("horaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoProductoField, value) != true)) {
                    this.codigoProductoField = value;
                    this.RaisePropertyChanged("codigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public TNT.WebSintesis_externo.DPlanilla[] planillas {
            get {
                return this.planillasField;
            }
            set {
                if ((object.ReferenceEquals(this.planillasField, value) != true)) {
                    this.planillasField = value;
                    this.RaisePropertyChanged("planillas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DPlanilla", Namespace="http://www.openuri.org/")]
    [System.SerializableAttribute()]
    public partial class DPlanilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int numeroPagoField;
        
        private double montoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        private double montoCreditoFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nitFacturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroPago {
            get {
                return this.numeroPagoField;
            }
            set {
                if ((this.numeroPagoField.Equals(value) != true)) {
                    this.numeroPagoField = value;
                    this.RaisePropertyChanged("numeroPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double montoPago {
            get {
                return this.montoPagoField;
            }
            set {
                if ((this.montoPagoField.Equals(value) != true)) {
                    this.montoPagoField = value;
                    this.RaisePropertyChanged("montoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double montoCreditoFiscal {
            get {
                return this.montoCreditoFiscalField;
            }
            set {
                if ((this.montoCreditoFiscalField.Equals(value) != true)) {
                    this.montoCreditoFiscalField = value;
                    this.RaisePropertyChanged("montoCreditoFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nombreFactura {
            get {
                return this.nombreFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreFacturaField, value) != true)) {
                    this.nombreFacturaField = value;
                    this.RaisePropertyChanged("nombreFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nitFactura {
            get {
                return this.nitFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.nitFacturaField, value) != true)) {
                    this.nitFacturaField = value;
                    this.RaisePropertyChanged("nitFactura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespPlanilla", Namespace="http://www.openuri.org/")]
    [System.SerializableAttribute()]
    public partial class RespPlanilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idTransaccionField;
        
        private int codErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.idTransaccionField, value) != true)) {
                    this.idTransaccionField = value;
                    this.RaisePropertyChanged("idTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int codError {
            get {
                return this.codErrorField;
            }
            set {
                if ((this.codErrorField.Equals(value) != true)) {
                    this.codErrorField = value;
                    this.RaisePropertyChanged("codError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionErrorField, value) != true)) {
                    this.descripcionErrorField = value;
                    this.RaisePropertyChanged("descripcionError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.openuri.org/", ConfigurationName="WebSintesis_externo.ComelecSoap")]
    public interface ComelecSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento datos del espacio de nombres http://www.openuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/cmeRegistroItem", ReplyAction="*")]
        TNT.WebSintesis_externo.cmeRegistroItemResponse cmeRegistroItem(TNT.WebSintesis_externo.cmeRegistroItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/cmeRegistroItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TNT.WebSintesis_externo.cmeRegistroItemResponse> cmeRegistroItemAsync(TNT.WebSintesis_externo.cmeRegistroItemRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento datos del espacio de nombres http://www.openuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/cmeRegistroPlan", ReplyAction="*")]
        TNT.WebSintesis_externo.cmeRegistroPlanResponse cmeRegistroPlan(TNT.WebSintesis_externo.cmeRegistroPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.openuri.org/cmeRegistroPlan", ReplyAction="*")]
        System.Threading.Tasks.Task<TNT.WebSintesis_externo.cmeRegistroPlanResponse> cmeRegistroPlanAsync(TNT.WebSintesis_externo.cmeRegistroPlanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cmeRegistroItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cmeRegistroItem", Namespace="http://www.openuri.org/", Order=0)]
        public TNT.WebSintesis_externo.cmeRegistroItemRequestBody Body;
        
        public cmeRegistroItemRequest() {
        }
        
        public cmeRegistroItemRequest(TNT.WebSintesis_externo.cmeRegistroItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.openuri.org/")]
    public partial class cmeRegistroItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TNT.WebSintesis_externo.DatosItem datos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cuenta;
        
        public cmeRegistroItemRequestBody() {
        }
        
        public cmeRegistroItemRequestBody(TNT.WebSintesis_externo.DatosItem datos, string cuenta) {
            this.datos = datos;
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cmeRegistroItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cmeRegistroItemResponse", Namespace="http://www.openuri.org/", Order=0)]
        public TNT.WebSintesis_externo.cmeRegistroItemResponseBody Body;
        
        public cmeRegistroItemResponse() {
        }
        
        public cmeRegistroItemResponse(TNT.WebSintesis_externo.cmeRegistroItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.openuri.org/")]
    public partial class cmeRegistroItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TNT.WebSintesis_externo.RespItem cmeRegistroItemResult;
        
        public cmeRegistroItemResponseBody() {
        }
        
        public cmeRegistroItemResponseBody(TNT.WebSintesis_externo.RespItem cmeRegistroItemResult) {
            this.cmeRegistroItemResult = cmeRegistroItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cmeRegistroPlanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cmeRegistroPlan", Namespace="http://www.openuri.org/", Order=0)]
        public TNT.WebSintesis_externo.cmeRegistroPlanRequestBody Body;
        
        public cmeRegistroPlanRequest() {
        }
        
        public cmeRegistroPlanRequest(TNT.WebSintesis_externo.cmeRegistroPlanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.openuri.org/")]
    public partial class cmeRegistroPlanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TNT.WebSintesis_externo.DatosPlanilla datos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cuenta;
        
        public cmeRegistroPlanRequestBody() {
        }
        
        public cmeRegistroPlanRequestBody(TNT.WebSintesis_externo.DatosPlanilla datos, string cuenta) {
            this.datos = datos;
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cmeRegistroPlanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cmeRegistroPlanResponse", Namespace="http://www.openuri.org/", Order=0)]
        public TNT.WebSintesis_externo.cmeRegistroPlanResponseBody Body;
        
        public cmeRegistroPlanResponse() {
        }
        
        public cmeRegistroPlanResponse(TNT.WebSintesis_externo.cmeRegistroPlanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.openuri.org/")]
    public partial class cmeRegistroPlanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TNT.WebSintesis_externo.RespPlanilla cmeRegistroPlanResult;
        
        public cmeRegistroPlanResponseBody() {
        }
        
        public cmeRegistroPlanResponseBody(TNT.WebSintesis_externo.RespPlanilla cmeRegistroPlanResult) {
            this.cmeRegistroPlanResult = cmeRegistroPlanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComelecSoapChannel : TNT.WebSintesis_externo.ComelecSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComelecSoapClient : System.ServiceModel.ClientBase<TNT.WebSintesis_externo.ComelecSoap>, TNT.WebSintesis_externo.ComelecSoap {
        
        public ComelecSoapClient() {
        }
        
        public ComelecSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComelecSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComelecSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComelecSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TNT.WebSintesis_externo.cmeRegistroItemResponse TNT.WebSintesis_externo.ComelecSoap.cmeRegistroItem(TNT.WebSintesis_externo.cmeRegistroItemRequest request) {
            return base.Channel.cmeRegistroItem(request);
        }
        
        public TNT.WebSintesis_externo.RespItem cmeRegistroItem(TNT.WebSintesis_externo.DatosItem datos, string cuenta) {
            TNT.WebSintesis_externo.cmeRegistroItemRequest inValue = new TNT.WebSintesis_externo.cmeRegistroItemRequest();
            inValue.Body = new TNT.WebSintesis_externo.cmeRegistroItemRequestBody();
            inValue.Body.datos = datos;
            inValue.Body.cuenta = cuenta;
            TNT.WebSintesis_externo.cmeRegistroItemResponse retVal = ((TNT.WebSintesis_externo.ComelecSoap)(this)).cmeRegistroItem(inValue);
            return retVal.Body.cmeRegistroItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TNT.WebSintesis_externo.cmeRegistroItemResponse> TNT.WebSintesis_externo.ComelecSoap.cmeRegistroItemAsync(TNT.WebSintesis_externo.cmeRegistroItemRequest request) {
            return base.Channel.cmeRegistroItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TNT.WebSintesis_externo.cmeRegistroItemResponse> cmeRegistroItemAsync(TNT.WebSintesis_externo.DatosItem datos, string cuenta) {
            TNT.WebSintesis_externo.cmeRegistroItemRequest inValue = new TNT.WebSintesis_externo.cmeRegistroItemRequest();
            inValue.Body = new TNT.WebSintesis_externo.cmeRegistroItemRequestBody();
            inValue.Body.datos = datos;
            inValue.Body.cuenta = cuenta;
            return ((TNT.WebSintesis_externo.ComelecSoap)(this)).cmeRegistroItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TNT.WebSintesis_externo.cmeRegistroPlanResponse TNT.WebSintesis_externo.ComelecSoap.cmeRegistroPlan(TNT.WebSintesis_externo.cmeRegistroPlanRequest request) {
            return base.Channel.cmeRegistroPlan(request);
        }
        
        public TNT.WebSintesis_externo.RespPlanilla cmeRegistroPlan(TNT.WebSintesis_externo.DatosPlanilla datos, string cuenta) {
            TNT.WebSintesis_externo.cmeRegistroPlanRequest inValue = new TNT.WebSintesis_externo.cmeRegistroPlanRequest();
            inValue.Body = new TNT.WebSintesis_externo.cmeRegistroPlanRequestBody();
            inValue.Body.datos = datos;
            inValue.Body.cuenta = cuenta;
            TNT.WebSintesis_externo.cmeRegistroPlanResponse retVal = ((TNT.WebSintesis_externo.ComelecSoap)(this)).cmeRegistroPlan(inValue);
            return retVal.Body.cmeRegistroPlanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TNT.WebSintesis_externo.cmeRegistroPlanResponse> TNT.WebSintesis_externo.ComelecSoap.cmeRegistroPlanAsync(TNT.WebSintesis_externo.cmeRegistroPlanRequest request) {
            return base.Channel.cmeRegistroPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<TNT.WebSintesis_externo.cmeRegistroPlanResponse> cmeRegistroPlanAsync(TNT.WebSintesis_externo.DatosPlanilla datos, string cuenta) {
            TNT.WebSintesis_externo.cmeRegistroPlanRequest inValue = new TNT.WebSintesis_externo.cmeRegistroPlanRequest();
            inValue.Body = new TNT.WebSintesis_externo.cmeRegistroPlanRequestBody();
            inValue.Body.datos = datos;
            inValue.Body.cuenta = cuenta;
            return ((TNT.WebSintesis_externo.ComelecSoap)(this)).cmeRegistroPlanAsync(inValue);
        }
    }
}
